/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CF;

import CF.telaEscolhaProjeto;
import CF.TelaLogin;

/**
 *
 * @author José Satiro
 */
public class telaFeedBackLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaFeedBackLogin.class.getName());

  
    /**
     * Creates new form telaLoginRealizado
     */
    
    private boolean loginRealizado;
    
    public telaFeedBackLogin(boolean loginRealizado) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        this.loginRealizado = loginRealizado;

        aplicarTela();
    }
    
    private void aplicarTela() {
        if (loginRealizado) {
            jPanel1.setBackground(new java.awt.Color(237, 252, 248));
            
            iconeTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/verificado (2).png"))); // NOI18N
            
            msgLogin.setForeground(new java.awt.Color(0, 79, 59));
            msgLogin.setText("Login realizado com sucesso");
            
            msgDesc.setForeground(new java.awt.Color(47, 148, 118));
            msgDesc.setText("Bem-vindo(a) ao sistema!");
            
            botaoTela.setBackground(new java.awt.Color(0, 183, 125));
            botaoTela.setForeground(new java.awt.Color(255, 255, 255));
            botaoTela.setText("Continuar");
        }
        else {
            jPanel1.setBackground(new java.awt.Color(255, 245, 242));
            
            iconeTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botao-excluir.png"))); // NOI18N
            
            msgLogin.setForeground(new java.awt.Color(130, 24, 26));
            msgLogin.setText("Usuário ou senha inválidos ");
            
            msgDesc.setForeground(new java.awt.Color(205, 49, 54));
            msgDesc.setText("Verifique seus dados e tente novamente.");
            
            botaoTela.setBackground(new java.awt.Color(249, 79, 81));
            botaoTela.setForeground(new java.awt.Color(255, 255, 255));
            botaoTela.setText("Tentar novamente");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconeTela = new javax.swing.JLabel();
        msgLogin = new javax.swing.JLabel();
        msgDesc = new javax.swing.JLabel();
        botaoTela = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 252, 248));

        iconeTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/verificado (2).png"))); // NOI18N

        msgLogin.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        msgLogin.setForeground(new java.awt.Color(0, 79, 59));
        msgLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLogin.setText("Login realizado com sucesso");

        msgDesc.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        msgDesc.setForeground(new java.awt.Color(47, 148, 118));
        msgDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgDesc.setText("Bem-vindo(a) ao sistema!");

        botaoTela.setBackground(new java.awt.Color(0, 183, 125));
        botaoTela.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        botaoTela.setForeground(new java.awt.Color(255, 255, 255));
        botaoTela.setText("Continuar");
        botaoTela.setBorder(null);
        botaoTela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoTela.setFocusPainted(false);
        botaoTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(msgDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(iconeTela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(botaoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(iconeTela)
                .addGap(18, 18, 18)
                .addComponent(msgLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msgDesc)
                .addGap(18, 18, 18)
                .addComponent(botaoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaActionPerformed
        // TODO add your handling code here:
        if (loginRealizado) {
            new telaEscolhaProjeto().setVisible(true);
            this.dispose();
        } else {
            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botaoTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
 
        java.awt.EventQueue.invokeLater(() -> new telaFeedBackLogin(true).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoTela;
    private javax.swing.JLabel iconeTela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msgDesc;
    private javax.swing.JLabel msgLogin;
    // End of variables declaration//GEN-END:variables
}
